name: prabhjot
favicon: null
layout_spectrum: 0.048533821012824774
typography_spectrum: 0.66661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#cecece'
    - '#070707'
    - '#6e6f73'
    - '#b1b1b1'
  brandStrength: 0.8125
  lightness: 0.2592901522293687
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
